import Link from "next/link";
import { ArrowRight, Download, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { MetricRow, ProductPageHeader, SectionHeading } from "@/components/product/page-primitives";
import { EmptyState } from "@/components/product/empty-state";
import { dateLabel, money, StatusBadge } from "@/components/product/status";
import { requireProductActor } from "@/server/auth/guards";
import { getDealerProductData } from "@/server/services/product";

export default async function DealerDashboardPage() {
  const actor = await requireProductActor(["DEALER_ADMIN", "DEALER_USER"]); const data = getDealerProductData(actor); const readiness = data.metrics.matchRate; const attention = data.exceptions.slice(0, 8);
  return <><ProductPageHeader eyebrow={data.reportingPeriod?.name ?? "Current period"} title="Compliance overview" description="The records, responses, and evidence your dealership needs to complete next." actions={<><Button variant="outline" asChild><a href="/api/reports/reconciliation"><Download className="size-4" /> Export</a></Button><Button asChild><Link href="/dealer/imports"><Upload className="size-4" /> Import records</Link></Button></>} /><MetricRow items={[{ label: "Reconciliation rate", value: `${readiness}%`, note: `${data.latestRun?.ruleVersion ?? "No run"} · ${dateLabel(data.latestRun?.completedAt)}` }, { label: "Transactions", value: data.metrics.totalTransactions.toLocaleString(), note: `${data.latestRun?.registrationRecordCount ?? 0} registration-style records` }, { label: "Open exceptions", value: data.metrics.openExceptions.toLocaleString(), note: `${data.metrics.highPriorityExceptions} high priority`, tone: data.metrics.highPriorityExceptions ? "danger" : "default" }, { label: "Unresolved fee impact", value: money(data.metrics.unresolvedFeeImpact), note: "Estimate until reviewed", tone: data.metrics.unresolvedFeeImpact ? "warning" : "default" }]} /><section className="mt-7 overflow-hidden border bg-background"><SectionHeading title="Action required" description="Highest-impact items from the latest reconciliation run." action={<Button variant="ghost" size="sm" asChild><Link href="/dealer/exceptions">View all <ArrowRight className="size-4" /></Link></Button>} />{attention.length ? <Table><TableHeader><TableRow><TableHead>VIN</TableHead><TableHead>Why it was flagged</TableHead><TableHead>Rule</TableHead><TableHead>Priority</TableHead><TableHead className="text-right">Fee impact</TableHead></TableRow></TableHeader><TableBody>{attention.map((item) => <TableRow key={item.id}><TableCell className="font-mono text-xs">…{item.vin.slice(-8)}</TableCell><TableCell><p className="max-w-lg font-medium">{item.type}</p><p className="mt-1 max-w-xl text-xs text-muted-foreground">{item.requirement}</p></TableCell><TableCell className="font-mono text-xs">{item.rule}</TableCell><TableCell><StatusBadge value={item.priority} /></TableCell><TableCell className="text-right font-mono">{money(item.feeImpact)}</TableCell></TableRow>)}</TableBody></Table> : <EmptyState kind="all-clear" title="Nothing needs attention" description="There are no open reconciliation items for this reporting period." />}</section></>;
}
