import { describe, expect, it } from "vitest";
import { reconcile, RULE_VERSION } from "../reconciliation/engine";
import type { ReconciliationRegistrationRecord, ReconciliationTransaction } from "../reconciliation/types";

const period = { id: "period-1", dealershipId: "dealer-1", startDate: "2025-01-01", endDate: "2025-12-31" };
const transaction = (override: Partial<ReconciliationTransaction> = {}): ReconciliationTransaction => ({ id: "txn-1", dealershipId: "dealer-1", vehicleId: "vehicle-1", reportingPeriodId: "period-1", vin: "2HG000000000000RS", normalizedVin: "2HG000000000000RS", transactionType: "RETAIL", transactionDate: "2025-05-10", feeRequired: true, expectedFee: 22, reportedFee: 22, transactionStatus: "ACTIVE", evidenceCount: 1, ...override });
const registration = (override: Partial<ReconciliationRegistrationRecord> = {}): ReconciliationRegistrationRecord => ({ id: "reg-1", dealershipId: "dealer-1", vehicleId: "vehicle-1", reportingPeriodId: "period-1", vin: "2HG000000000000RS", normalizedVin: "2HG000000000000RS", registrationDate: "2025-05-12", eventType: "REGISTRATION", ...override });

describe("deterministic reconciliation", () => {
  it("creates an exact VIN match", () => { const result = reconcile({ period, transactions: [transaction()], registrationRecords: [registration()] }); expect(result.matches[0].matchType).toBe("EXACT"); expect(result.exceptions).toEqual([]); expect(result.transactionOutcomes[0].state).toBe("MATCHED"); });
  it("flags a date variance outside tolerance", () => { const result = reconcile({ period, transactions: [transaction()], registrationRecords: [registration({ registrationDate: "2025-06-01" })] }); expect(result.exceptions.map((item) => item.ruleId)).toContain("DATE001"); expect(result.matches[0].matchType).toBe("EXACT_WITH_DATE_VARIANCE"); });
  it("creates missing transaction and missing registration exceptions", () => { expect(reconcile({ period, transactions: [], registrationRecords: [registration()] }).exceptions[0].ruleId).toBe("TXN001"); expect(reconcile({ period, transactions: [transaction()], registrationRecords: [] }).exceptions.map((item) => item.ruleId)).toContain("TXN002"); });
  it("detects duplicate VINs in the same context", () => { const result = reconcile({ period, transactions: [transaction(), transaction({ id: "txn-2" })], registrationRecords: [registration()] }); expect(result.exceptions.filter((item) => item.ruleId === "TXN003")).toHaveLength(2); });
  it("flags missing and mismatched fees", () => { expect(reconcile({ period, transactions: [transaction({ reportedFee: 0 })], registrationRecords: [registration()] }).exceptions.map((item) => item.ruleId)).toContain("FEE001"); expect(reconcile({ period, transactions: [transaction({ reportedFee: 10 })], registrationRecords: [registration()] }).exceptions.map((item) => item.ruleId)).toContain("FEE002"); });
  it("requires evidence for configured exception classifications", () => { const result = reconcile({ period, transactions: [transaction({ transactionType: "WHOLESALE", feeRequired: false, expectedFee: 0, reportedFee: 0, evidenceCount: 0 })], registrationRecords: [registration()] }); expect(result.exceptions.map((item) => item.ruleId)).toContain("DOC001"); });
  it("classifies out-of-period transactions and preserves rule version", () => { const result = reconcile({ period, transactions: [transaction({ transactionDate: "2026-01-02" })], registrationRecords: [registration({ registrationDate: "2026-01-03" })] }); expect(result.exceptions.map((item) => item.ruleId)).toContain("PERIOD001"); expect(result.ruleVersion).toBe(RULE_VERSION); });
  it("is repeatable for identical input", () => { const input = { period, transactions: [transaction()], registrationRecords: [registration()] }; expect(reconcile(input)).toEqual(reconcile(input)); });
});
