import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { MetricRow, ProductPageHeader, SectionHeading } from "@/components/product/page-primitives";
import { EmptyState } from "@/components/product/empty-state";
import { dateLabel, money, StatusBadge } from "@/components/product/status";
import { requireProductActor } from "@/server/auth/guards";
import { getReviewerProductData } from "@/server/services/product";

export default async function ReviewerDashboardPage() {
  await requireProductActor(["REGULATOR_REVIEWER"]); const data = getReviewerProductData(); const attention = [...data.dealerships].sort((a, b) => b.highPriority - a.highPriority || b.openExceptions - a.openExceptions).slice(0, 10);
  return <><ProductPageHeader eyebrow="Ontario review portfolio" title="Review overview" description="Prioritized dealership work, responses, audits, and potential fee impact for your assigned review context." actions={<Button asChild><Link href="/reviewer/exceptions">Open investigation queue <ArrowRight className="size-4" /></Link></Button>} /><MetricRow items={[{ label: "Dealerships", value: data.metrics.dealerships.toLocaleString(), note: "Current accessible portfolio" }, { label: "Open exceptions", value: data.metrics.openExceptions.toLocaleString(), note: `${data.metrics.highPriority} high priority`, tone: data.metrics.highPriority ? "danger" : "default" }, { label: "Responses received", value: data.metrics.responsesReceived.toLocaleString(), note: "Ready for reviewer action" }, { label: "Estimated fee impact", value: money(data.metrics.estimatedFeeImpact), note: `${data.metrics.activeAudits} active audits`, tone: "warning" }]} /><section className="mt-7 overflow-hidden border bg-background"><SectionHeading title="Dealerships requiring attention" description="Ranked by high-priority and unresolved exceptions." action={<Button variant="ghost" size="sm" asChild><Link href="/reviewer/dealerships">All dealerships <ArrowRight className="size-4" /></Link></Button>} />{attention.length ? <Table><TableHeader><TableRow><TableHead>Dealership</TableHead><TableHead>Registration</TableHead><TableHead>Match rate</TableHead><TableHead>Open items</TableHead><TableHead>High priority</TableHead><TableHead className="text-right">Estimated impact</TableHead></TableRow></TableHeader><TableBody>{attention.map((item) => <TableRow key={item.id}><TableCell><p className="font-medium">{item.tradeName}</p><p className="mt-1 text-xs text-muted-foreground">{item.city}, {item.province} · Last run {dateLabel(item.lastRunAt)}</p></TableCell><TableCell className="font-mono text-xs">{item.registrationNumber}</TableCell><TableCell>{item.matchRate === null ? "No run" : `${item.matchRate}%`}</TableCell><TableCell>{item.openExceptions}</TableCell><TableCell>{item.highPriority ? <StatusBadge value={`${item.highPriority} high`} /> : "—"}</TableCell><TableCell className="text-right font-mono">{money(item.estimatedFeeImpact)}</TableCell></TableRow>)}</TableBody></Table> : <EmptyState kind="all-clear" title="No dealerships need attention" description="The assigned portfolio has no unresolved priority work." />}</section></>;
}
