"use client";

import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { CategoryDatum, TimeSeriesDatum } from "@/domain/product/ui-system";

type Datum = CategoryDatum | TimeSeriesDatum;
const compact = (value: number) => new Intl.NumberFormat("en-CA", { notation: "compact", maximumFractionDigits: 1 }).format(value);

export function ChartCard({ title, description, data, kind, summary }: { title: string; description: string; data: Datum[]; kind: "line" | "bar"; summary: string }) {
  const hasData = data.some((item) => typeof item.value === "number" && item.value > 0);
  return <section className="rounded-[14px] border bg-white p-5"><div><h2 className="text-base font-medium leading-6 text-foreground">{title}</h2><p className="mt-0.5 text-[13px] leading-4 text-secondary-foreground">{description}</p></div><div className="mt-5 h-56" role="img" aria-label={summary}>{hasData ? <ResponsiveContainer width="100%" height="100%">{kind === "line" ? <LineChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: -18 }}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 4" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tickFormatter={compact} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} /><Tooltip content={<ChartTooltip />} cursor={{ stroke: "var(--input-hover)", strokeDasharray: "3 3" }} /><Line type="monotone" dataKey="value" stroke="var(--chart-1)" strokeWidth={2} dot={false} activeDot={{ r: 4, fill: "var(--chart-1)" }} connectNulls={false} isAnimationActive animationDuration={220} /></LineChart> : <BarChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: -18 }}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 4" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tickFormatter={compact} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} /><Tooltip content={<ChartTooltip />} cursor={{ fill: "var(--input-hover)" }} /><Bar dataKey="value" fill="var(--chart-2)" radius={[6,6,0,0]} isAnimationActive animationDuration={220} maxBarSize={44} /></BarChart>}</ResponsiveContainer> : <div className="flex h-full flex-col items-center justify-center text-[13px] text-muted-foreground"><span className="mb-3 block w-full border-t border-dashed" />No data for this period</div>}</div><p className="mt-3 text-xs text-muted-foreground">{summary}</p><table className="sr-only"><caption>{title} data</caption><thead><tr><th>Category</th><th>Value</th></tr></thead><tbody>{data.map((item) => <tr key={item.key}><th>{item.label}</th><td>{item.value ?? "Unavailable"}</td></tr>)}</tbody></table></section>;
}

function ChartTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value?: number }>; label?: string }) { if (!active || !payload?.length) return null; return <div className="rounded-lg border bg-white px-3 py-2 text-xs"><p className="text-muted-foreground">{label}</p><strong className="mt-1 block font-medium text-foreground tabular-nums">{Number(payload[0].value ?? 0).toLocaleString("en-CA")}</strong></div>; }
