"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, CheckCircle2, FileUp, LoaderCircle, Upload } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SegmentedControl } from "@/components/ui/segmented-control";

type Preview = { mapping: Record<string, string>; summary: { totalRows: number; validRows: number; warningRows: number; rejectedRows: number; duplicateRows: number } };
export function DealerImportPanel({ dealershipId, reportingPeriodId }: { dealershipId: string; reportingPeriodId: string }) {
  const router = useRouter(); const [file, setFile] = useState<File | null>(null); const [sourceType, setSourceType] = useState<"TRANSACTION_REGISTER" | "REGISTRATION_RECORD">("TRANSACTION_REGISTER"); const [preview, setPreview] = useState<Preview | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function request(mode: "preview" | "commit") { if (!file) return; setBusy(true); setError(""); const form = new FormData(); form.set("file", file); form.set("sourceType", sourceType); form.set("mode", mode); form.set("dealershipId", dealershipId); form.set("reportingPeriodId", reportingPeriodId); if (preview) form.set("mapping", JSON.stringify(preview.mapping)); try { const response = await fetch("/api/imports", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (mode === "preview") setPreview(body); else { setFile(null); setPreview(null); router.refresh(); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Import failed."); } finally { setBusy(false); } }
  return <section className="rounded-[14px] border bg-white p-5"><div className="mb-5 flex items-start gap-3 border-b pb-5"><span className="grid size-10 shrink-0 place-items-center rounded-[10px] border bg-muted text-muted-foreground"><FileUp className="size-4" /></span><div><h2 className="text-base font-medium text-foreground">{error ? "Choose another source file" : "Add source records"}</h2><p className="mt-1 max-w-xl text-[13px] leading-4 text-secondary-foreground">{error ? "The previous file could not be validated. Review the message below and try another CSV." : "Select the source type and choose a CSV. DealerSync previews every row before anything is committed."}</p></div></div><div className="grid gap-4 md:grid-cols-[300px_1fr_auto] md:items-end"><div className="space-y-1.5"><Label>Source type</Label><SegmentedControl value={sourceType} onValueChange={(value) => { setSourceType(value); setPreview(null); }} ariaLabel="Source type" className="w-full" options={[{ value: "TRANSACTION_REGISTER", label: "Transactions" }, { value: "REGISTRATION_RECORD", label: "Registrations" }]} /></div><div className="space-y-1.5"><Label htmlFor="csv-file">CSV file</Label><Input id="csv-file" type="file" accept=".csv,text/csv" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); }} /></div><Button disabled={!file || busy} onClick={() => void request("preview")}>{busy ? <LoaderCircle className="size-3.5 animate-spin" /> : <Upload className="size-4" />}{busy ? "Checking" : "Validate file"}</Button></div>{error ? <Alert variant="destructive" className="mt-4"><AlertCircle className="size-4" /><AlertDescription>{error}</AlertDescription></Alert> : null}{preview ? <div className="mt-5 border-t pt-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="flex items-center gap-2 text-[13px] font-medium"><CheckCircle2 className="size-4" /> Validation complete</p><p className="mt-1 text-xs text-muted-foreground">{preview.summary.validRows} valid · {preview.summary.warningRows} warnings · {preview.summary.rejectedRows} rejected · {preview.summary.duplicateRows} duplicates</p></div><Button disabled={busy || preview.summary.validRows + preview.summary.warningRows === 0} onClick={() => void request("commit")}>{busy ? <><LoaderCircle className="size-3.5 animate-spin" /> Importing</> : `Import ${preview.summary.validRows + preview.summary.warningRows} rows`}</Button></div><dl className="mt-4 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-3">{Object.entries(preview.mapping).map(([field, column]) => <div key={field} className="flex items-center justify-between gap-3 rounded-lg border bg-muted px-3 py-2"><dt className="text-muted-foreground">{column}</dt><dd className="font-medium text-foreground">{field.replaceAll("_", " ")}</dd></div>)}</dl></div> : null}</section>;
}
