"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, LoaderCircle, Upload } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function DocumentUploadDialog({ dealershipId }: { dealershipId: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [file, setFile] = useState<File | null>(null); const [type, setType] = useState("SUPPORTING_EVIDENCE"); const [transactionId, setTransactionId] = useState(""); const [exceptionId, setExceptionId] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!file) { setError("Choose a document to upload."); return; } setBusy(true); setError(""); const form = new FormData(); form.set("file", file); form.set("dealershipId", dealershipId); form.set("documentType", type); if (transactionId.trim()) form.set("transactionId", transactionId.trim()); if (exceptionId.trim()) form.set("exceptionId", exceptionId.trim()); try { const response = await fetch("/api/documents", { method: "POST", body: form }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Upload failed."); setOpen(false); setFile(null); setTransactionId(""); setExceptionId(""); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed."); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Upload className="size-4" /> Upload evidence</Button></DialogTrigger><DialogContent className="top-1/2 max-w-md -translate-y-1/2"><div className="border-b p-5 pr-12"><DialogTitle>Upload evidence</DialogTitle><DialogDescription>Attach a supported document inside this dealership workspace.</DialogDescription></div><form onSubmit={submit} className="space-y-4 p-5">{error ? <Alert variant="destructive"><AlertCircle className="size-4" /><AlertDescription>{error}</AlertDescription></Alert> : null}<div className="space-y-1.5"><Label htmlFor="evidence-file">File</Label><Input id="evidence-file" type="file" accept=".pdf,.csv,.xlsx,.xls,.doc,.docx,.jpg,.jpeg,.png" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></div><div className="space-y-1.5"><Label>Document type</Label><Select value={type} onValueChange={setType}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="SUPPORTING_EVIDENCE">Supporting evidence</SelectItem><SelectItem value="BILL_OF_SALE">Bill of sale</SelectItem><SelectItem value="REGISTRATION">Registration</SelectItem><SelectItem value="CORRESPONDENCE">Correspondence</SelectItem></SelectContent></Select></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="transaction-id">Transaction ID</Label><Input id="transaction-id" value={transactionId} onChange={(event) => setTransactionId(event.target.value)} placeholder="Optional" /></div><div className="space-y-1.5"><Label htmlFor="exception-id">Exception ID</Label><Input id="exception-id" value={exceptionId} onChange={(event) => setExceptionId(event.target.value)} placeholder="Optional" /></div></div><div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? <><LoaderCircle className="size-3.5 animate-spin" /> Uploading</> : "Upload evidence"}</Button></div></form></DialogContent></Dialog>;
}
