"use client";

import { useEffect, useRef, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { FileArchive, FileText, Gavel, Search, ShieldAlert, Store, Rows3 } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { StatusBadge } from "@/components/product/status";
import { entityHref } from "@/product/entity-navigation";
import { isSearchableQuery, type GlobalSearchResult } from "@/product/search";

const iconByType = { dealership: Store, transaction: Rows3, exception: ShieldAlert, document: FileText, import: FileArchive, audit: Gavel, run: Rows3 };

export function GlobalSearch({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const [query, setQuery] = useState(""); const [results, setResults] = useState<GlobalSearchResult[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [active, setActive] = useState(0); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!open) { setQuery(""); setResults([]); setError(""); return; } window.setTimeout(() => inputRef.current?.focus(), 20); }, [open]);
  useEffect(() => { if (!isSearchableQuery(query)) { setResults([]); setLoading(false); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { setLoading(true); setError(""); fetch(`/api/search?q=${encodeURIComponent(query)}`, { signal: controller.signal }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Search is unavailable."); setResults((payload.results ?? []).slice(0, 8)); setActive(0); }).catch((reason) => { if (reason.name !== "AbortError") setError(reason instanceof Error ? reason.message : "Search is unavailable."); }).finally(() => setLoading(false)); }, 180); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query]);
  const select = (result: GlobalSearchResult) => { const current = `${pathname}${params.size ? `?${params.toString()}` : ""}`; onOpenChange(false); router.push(entityHref(current, result.type, result.id), { scroll: false }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent aria-describedby="global-search-description" onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setActive((value) => Math.min(value + 1, results.length - 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((value) => Math.max(value - 1, 0)); } if (event.key === "Enter" && results[active]) { event.preventDefault(); select(results[active]); } }}><div className="border-b p-4 pr-12"><DialogTitle>Search records</DialogTitle><DialogDescription id="global-search-description">Find authorized dealerships, VINs, exceptions, audits, imports, and documents.</DialogDescription></div><div className="relative border-b p-3"><Search className="pointer-events-none absolute left-6 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /><Input ref={inputRef} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search VIN or record" aria-label="Search VIN or record" className="pl-9" /></div><div className="max-h-64 overflow-y-auto p-2" role="listbox" aria-label="Search results">{query.trim().length < 2 ? <SearchState>Type at least two characters to search.</SearchState> : loading ? <div className="space-y-1 p-2">{[0,1,2].map((item) => <div key={item} className="h-8 animate-pulse rounded-md bg-muted" />)}</div> : error ? <SearchState>{error}</SearchState> : results.length ? results.slice(0, 8).map((result, index) => { const Icon = iconByType[result.type]; return <button key={`${result.type}-${result.id}`} type="button" role="option" aria-selected={index === active} onMouseEnter={() => setActive(index)} onClick={() => select(result)} className="flex min-h-12 w-full items-center gap-3 rounded-lg px-3 py-2 text-left aria-selected:bg-muted"><span className="grid size-8 shrink-0 place-items-center rounded-lg border bg-background"><Icon className="size-3.5 text-muted-foreground" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-[13px] font-normal text-foreground"><HighlightedText text={result.primaryLabel} query={query} /></strong><small className="block truncate text-xs text-muted-foreground">{result.secondaryLabel}</small></span>{result.status ? <StatusBadge value={result.status} /> : null}</button>; }) : <SearchState>No matches</SearchState>}</div><div className="flex items-center gap-4 border-t px-4 py-2 text-xs text-muted-foreground"><span>↑↓ Navigate</span><span>↵ Open</span><span>Esc Close</span></div></DialogContent></Dialog>;
}

function HighlightedText({ text, query }: { text: string; query: string }) { const match = text.toLowerCase().indexOf(query.trim().toLowerCase()); if (match < 0) return text; return <>{text.slice(0, match)}<span className="font-medium">{text.slice(match, match + query.trim().length)}</span>{text.slice(match + query.trim().length)}</>; }

function SearchState({ children }: { children: React.ReactNode }) { return <div className="grid place-items-center px-6 py-8 text-center text-[13px] text-muted-foreground">{children}</div>; }
