"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { ChevronDown, FileArchive, FileText, Gauge, Gavel, Import, LayoutDashboard, LogOut, Menu, Rows3, Search, Settings, ShieldCheck, Store, TriangleAlert, Users } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import type { ProductNavigationItem } from "@/product/navigation";

const icons: Record<string, React.ComponentType<{ className?: string }>> = { Overview: LayoutDashboard, Transactions: Rows3, Exceptions: TriangleAlert, Imports: Import, Documents: FileArchive, Reports: FileText, Dealerships: Store, Audits: Gavel };

function Navigation({ items, onNavigate }: { items: ProductNavigationItem[]; onNavigate?: () => void }) {
  const pathname = usePathname();
  return <nav className="space-y-1" aria-label="Product navigation">{items.map((item) => { const Icon = icons[item.label] ?? Gauge; const active = pathname === item.href || pathname.startsWith(`${item.href}/`); return <Link key={item.href} href={item.href} onClick={onNavigate} className={`flex min-h-10 items-center gap-3 rounded-md px-3 text-sm font-medium transition-colors ${active ? "bg-sidebar-accent text-sidebar-accent-foreground" : "text-sidebar-foreground/70 hover:bg-sidebar-accent/70 hover:text-sidebar-foreground"}`}><Icon className="size-4" /><span>{item.label}</span></Link>; })}</nav>;
}

export function ProductShell({ productLabel, contextLabel, items, user, children }: { productLabel: string; contextLabel: string; items: ProductNavigationItem[]; user: { name: string; email: string }; children: React.ReactNode }) {
  const router = useRouter(); const [mobileOpen, setMobileOpen] = useState(false); const initials = user.name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  async function signOut() { await fetch("/api/auth/sign-out", { method: "POST" }); router.push("/sign-in"); router.refresh(); }
  const sidebar = <><div className="border-b border-sidebar-border px-5 py-5"><Link href={items[0].href} className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground"><ShieldCheck className="size-4" /></span><span><strong className="block text-sm tracking-tight text-sidebar-foreground">DealerSync</strong><small className="block text-[11px] text-sidebar-foreground/55">{productLabel}</small></span></Link></div><div className="border-b border-sidebar-border px-5 py-4"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-sidebar-foreground/45">Current context</p><p className="mt-1 truncate text-sm font-medium text-sidebar-foreground">{contextLabel}</p></div><div className="flex-1 px-3 py-4"><Navigation items={items} onNavigate={() => setMobileOpen(false)} /></div><div className="border-t border-sidebar-border p-3"><Link href="#" className="flex min-h-10 items-center gap-3 rounded-md px-3 text-sm font-medium text-sidebar-foreground/65 hover:bg-sidebar-accent hover:text-sidebar-foreground"><Settings className="size-4" /> Settings</Link></div></>;
  return <div className="min-h-screen bg-muted/35 text-foreground"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-sidebar-border bg-sidebar lg:flex">{sidebar}</aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center gap-3 border-b bg-background/95 px-4 backdrop-blur sm:px-6 lg:px-8"><Sheet open={mobileOpen} onOpenChange={setMobileOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden"><Menu className="size-5" /><span className="sr-only">Open navigation</span></Button></SheetTrigger><SheetContent side="left" className="flex w-72 flex-col border-sidebar-border bg-sidebar p-0"><SheetHeader className="sr-only"><SheetTitle>Product navigation</SheetTitle></SheetHeader>{sidebar}</SheetContent></Sheet><button className="hidden min-w-64 items-center gap-2 rounded-md border bg-muted/30 px-3 py-2 text-left text-sm text-muted-foreground md:flex"><Search className="size-4" /> Search VIN or record<span className="ml-auto rounded border bg-background px-1.5 py-0.5 font-mono text-[10px]">⌘K</span></button><div className="ml-auto"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="h-10 gap-2 px-2"><Avatar className="size-7"><AvatarFallback className="text-[11px]">{initials}</AvatarFallback></Avatar><span className="hidden max-w-40 truncate text-sm sm:inline">{user.name}</span><ChevronDown className="size-3.5 text-muted-foreground" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-56"><DropdownMenuLabel><span className="block font-medium">{user.name}</span><span className="block truncate text-xs font-normal text-muted-foreground">{user.email}</span></DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem><Users className="size-4" /> Account settings</DropdownMenuItem><DropdownMenuItem onSelect={() => void signOut()}><LogOut className="size-4" /> Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header><main className="mx-auto w-full max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">{children}</main></div></div>;
}
