"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ChevronDown, FileArchive, FileText, Gavel, Import, LayoutDashboard, LogOut, Rows3, Search, ShieldCheck, Store, TriangleAlert } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { EntityDrawer } from "@/components/product/entity-drawer";
import { GlobalSearch } from "@/components/product/global-search";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarRail, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import type { ProductNavigationGroup } from "@/product/navigation";

const icons: Record<string, React.ComponentType<{ className?: string }>> = { Overview: LayoutDashboard, Transactions: Rows3, Exceptions: TriangleAlert, Imports: Import, Documents: FileArchive, Reports: FileText, Dealerships: Store, Audits: Gavel };
const pageNames: Record<string, string> = { dashboard: "Overview", transactions: "Transactions", exceptions: "Exceptions", imports: "Imports", documents: "Documents", reports: "Reports", dealerships: "Dealerships", audits: "Audits" };

function ProductNavigation({ groups }: { groups: ProductNavigationGroup[] }) {
  const pathname = usePathname(); const { setOpenMobile } = useSidebar();
  return <SidebarContent>{groups.map((group) => <SidebarGroup key={group.label} className="px-3 py-2"><SidebarGroupLabel className="h-7 px-2 text-xs font-medium text-muted-foreground group-data-[collapsible=icon]:hidden">{group.label}</SidebarGroupLabel><SidebarGroupContent><SidebarMenu className="gap-1">{group.items.map((item) => { const Icon = icons[item.label] ?? LayoutDashboard; const active = pathname === item.href || pathname.startsWith(`${item.href}/`); return <SidebarMenuItem key={item.href}><SidebarMenuButton asChild isActive={active} tooltip={{ children: item.label, side: "right", sideOffset: 10 }} className="h-8 rounded-lg px-2 text-xs font-normal text-muted-foreground data-[active=true]:border data-[active=true]:bg-muted data-[active=true]:font-medium data-[active=true]:text-foreground hover:text-foreground"><Link href={item.href} title={item.label} onClick={() => setOpenMobile(false)} aria-current={active ? "page" : undefined}><Icon className="size-4" /><span>{item.label}</span></Link></SidebarMenuButton>{typeof item.count === "number" ? <SidebarMenuBadge className="bg-transparent text-xs font-normal text-muted-foreground">{item.count > 99 ? "99+" : item.count}</SidebarMenuBadge> : null}</SidebarMenuItem>; })}</SidebarMenu></SidebarGroupContent></SidebarGroup>)}</SidebarContent>;
}

function AccountCell({ user, signOut }: { user: { name: string; email: string }; signOut: () => void }) {
  const initials = user.name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  return <DropdownMenu><DropdownMenuTrigger asChild><SidebarMenuButton size="lg" className="h-12 rounded-lg px-2"><Avatar className="size-7"><AvatarFallback className="bg-white text-xs">{initials}</AvatarFallback></Avatar><span className="min-w-0 flex-1"><strong className="block truncate text-xs font-medium text-foreground">{user.name}</strong><small className="block truncate text-xs font-normal text-muted-foreground">{user.email}</small></span><ChevronDown className="size-3.5 text-muted-foreground" /></SidebarMenuButton></DropdownMenuTrigger><DropdownMenuContent side="top" align="start" className="w-56"><DropdownMenuLabel className="text-xs font-medium">Signed in as {user.name}</DropdownMenuLabel><DropdownMenuItem variant="destructive" onSelect={signOut}><LogOut className="size-4" /> Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
}

export function ProductShell({ productLabel, contextLabel, groups, user, navigationCount, defaultSidebarOpen = true, children }: { productLabel: string; contextLabel: string; groups: ProductNavigationGroup[]; user: { name: string; email: string; role: string }; navigationCount?: number; defaultSidebarOpen?: boolean; children: React.ReactNode }) {
  const router = useRouter(); const pathname = usePathname(); const [searchOpen, setSearchOpen] = useState(false);
  useEffect(() => { const listener = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setSearchOpen(true); } }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, []);
  const countedGroups = groups.map((group) => ({ ...group, items: group.items.map((item) => item.label === "Exceptions" && typeof navigationCount === "number" ? { ...item, count: navigationCount } : item) }));
  async function signOut() { await fetch("/api/auth/sign-out", { method: "POST" }); router.push("/sign-in"); router.refresh(); }
  const segment = pathname.split("/").filter(Boolean).at(-1) ?? "dashboard"; const pageName = pageNames[segment] ?? segment;
  return <SidebarProvider defaultOpen={defaultSidebarOpen} className="product-app bg-background text-foreground"><Sidebar collapsible="icon" className="z-20 border-sidebar-border"><SidebarHeader className="h-14 justify-center border-b px-4 py-0"><Link href={countedGroups[0].items[0].href} className="flex min-w-0 items-center gap-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-primary text-primary-foreground"><ShieldCheck className="size-4" /></span><span className="min-w-0 group-data-[collapsible=icon]:hidden"><strong className="block truncate text-[13px] font-medium">DealerSync</strong><small className="block truncate text-xs text-muted-foreground">{productLabel}</small></span></Link></SidebarHeader><div className="border-b px-4 py-4 group-data-[collapsible=icon]:hidden"><p className="text-xs font-medium text-muted-foreground">Current context</p><p className="mt-1 truncate text-[13px] font-medium" title={contextLabel}>{contextLabel}</p></div><ProductNavigation groups={countedGroups} /><SidebarFooter className="border-t p-2"><SidebarMenu><SidebarMenuItem><AccountCell user={user} signOut={() => void signOut()} /></SidebarMenuItem></SidebarMenu></SidebarFooter><SidebarRail /></Sidebar><SidebarInset className="min-w-0 bg-background"><header className="sticky top-0 z-10 flex h-14 items-center gap-3 border-b bg-white px-4 sm:px-6 xl:px-8"><SidebarTrigger className="shrink-0" /><nav aria-label="Breadcrumb" className="min-w-0 text-xs"><span className="text-muted-foreground">{productLabel.replace(" workspace", "")}</span><span className="px-2 text-border">/</span><strong className="font-medium">{pageName}</strong></nav><Button type="button" variant="outline" onClick={() => setSearchOpen(true)} className="ml-auto hidden w-64 justify-start text-muted-foreground md:flex"><Search className="size-4" />Search VIN or record<span className="ml-auto rounded-md border bg-muted px-1.5 py-0.5 text-[11px]">⌘K</span></Button><Button type="button" variant="ghost" size="icon" onClick={() => setSearchOpen(true)} className="ml-auto md:hidden"><Search className="size-4" /><span className="sr-only">Search records</span></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Account menu for ${user.name}`}><Avatar className="size-7"><AvatarFallback className="text-xs">{user.name.split(" ").map((part) => part[0]).slice(0,2).join("")}</AvatarFallback></Avatar></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel className="text-xs font-medium">{user.name}</DropdownMenuLabel><DropdownMenuItem onSelect={() => void signOut()}><LogOut className="size-4" /> Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header><main className="mx-auto w-full max-w-[1440px] flex-1 px-4 py-6 sm:px-6 xl:px-8">{children}</main></SidebarInset><GlobalSearch open={searchOpen} onOpenChange={setSearchOpen} /><EntityDrawer role={user.role} /></SidebarProvider>;
}
