"use client";

import { useState } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { FilterX, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Option = { value: string; label: string };
type Props = { searchPlaceholder: string; filterLabel?: string; filterKey?: string; filterOptions?: Option[]; sortOptions?: Option[]; defaultSort?: string; page: number; pageCount: number; total: number };

export function TableToolbar({ searchPlaceholder, filterLabel, filterKey = "status", filterOptions = [], sortOptions, defaultSort, page, pageCount, total }: Props) {
  const pathname = usePathname(); const current = useSearchParams(); const router = useRouter(); const [query, setQuery] = useState(current.get("q") ?? ""); const filter = current.get(filterKey) ?? "all"; const sort = current.get("sort") ?? defaultSort ?? ""; const activeCount = Number(Boolean(current.get("q"))) + Number(Boolean(current.get(filterKey))) + Number(Boolean(current.get("sort") && current.get("sort") !== defaultSort));
  function update(key: string, value?: string) { const params = new URLSearchParams(current.toString()); if (value && value !== "all" && value !== defaultSort) params.set(key, value); else params.delete(key); params.delete("page"); params.delete("entity"); params.delete("entityId"); router.push(`${pathname}${params.size ? `?${params.toString()}` : ""}`); }
  function search() { update("q", query.trim()); }
  function clear() { setQuery(""); router.push(pathname); }
  function pageHref(nextPage: number) { const params = new URLSearchParams(current.toString()); params.set("page", String(nextPage)); params.delete("entity"); params.delete("entityId"); return `${pathname}?${params.toString()}`; }
  return <><div className="flex flex-col gap-3 rounded-t-[14px] border border-b-0 bg-white p-3 lg:flex-row lg:items-center"><div className="flex min-w-0 items-center gap-2 overflow-x-auto">{filterLabel ? <Select value={filter} onValueChange={(value) => update(filterKey, value)}><SelectTrigger treatment="filter" className="w-52 shrink-0" aria-label={filterLabel}><SelectValue placeholder={filterLabel} /></SelectTrigger><SelectContent><SelectItem value="all">All {filterLabel.toLowerCase()}</SelectItem>{filterOptions.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select> : null}{activeCount > 0 ? <Button variant="ghost" size="xs" onClick={clear} className="shrink-0"><FilterX className="size-3" /> Clear all</Button> : null}</div><div className="flex min-w-0 flex-1 gap-2 lg:justify-end">{sortOptions?.length ? <Select value={sort} onValueChange={(value) => update("sort", value)}><SelectTrigger treatment="filter" className="w-44 shrink-0" aria-label="Sort records"><SelectValue placeholder="Sort" /></SelectTrigger><SelectContent>{sortOptions.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select> : null}<div className="relative min-w-0 flex-1 lg:max-w-xs"><Search className="pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") search(); }} placeholder={searchPlaceholder} aria-label={searchPlaceholder} className="pl-9 pr-9" /><button type="button" onClick={search} className="absolute right-1 top-1 grid size-7 place-items-center rounded-md text-muted-foreground hover:bg-muted" aria-label="Search"><Search className="size-3.5" /></button></div></div></div><div className="flex min-h-11 items-center gap-2 border-x bg-white px-3 text-xs text-muted-foreground" aria-live="polite"><span>{total.toLocaleString()} records · Page {page} of {pageCount}</span><div className="ml-auto flex gap-2"><Button variant="outline" size="sm" asChild={page > 1} disabled={page <= 1}>{page > 1 ? <Link href={pageHref(page - 1)}>Previous</Link> : <span>Previous</span>}</Button><Button variant="outline" size="sm" asChild={page < pageCount} disabled={page >= pageCount}>{page < pageCount ? <Link href={pageHref(page + 1)}>Next</Link> : <span>Next</span>}</Button></div></div></>;
}
