"""
Distills scripts/nlp_output/{chunks,summary}.json (gitignored, regenerated by
pipeline.py) into data/nlp-analysis.json (committed, small) for the /analysis
page — same pattern as scripts/crawl_sources.py feeding data/research-findings.json.

Applies one manual QA step: two of the six zero-shot-tagged chunks turned out
to be nav artifacts (an OMVIC main-menu list and an OLA breadcrumb trail) that
slipped past the automatic nav filter in chunking.py because they contain a
couple of common words. Per the deep-research report's own exception-triage
design (human QA before anything reaches an investigation queue), those are
excluded here by chunk_id rather than presented as findings.
"""

import json
from pathlib import Path

NLP_OUTPUT = Path(__file__).parent.parent / "nlp_output"
DATA_DIR = Path(__file__).parent.parent.parent / "data"

EXCLUDED_CHUNK_IDS = {
    "ola-public-accounts-omvic-2023::2",  # breadcrumb nav trail, not content
    "omvic-garage-register::1",  # OMVIC main-menu list ("Buying", "Find a dealer"...)
}


def main() -> None:
    chunks = json.loads((NLP_OUTPUT / "chunks.json").read_text(encoding="utf-8"))
    summary = json.loads((NLP_OUTPUT / "summary.json").read_text(encoding="utf-8"))

    findings = [
        {
            "chunkId": c["chunk_id"],
            "sourceLabel": c["source_label"],
            "sourceUrl": c["source_url"],
            "text": c["text"],
            "label": c["taxonomy"][0]["label"],
            "score": c["taxonomy"][0]["score"],
            "sentiment": c["sentiment"]["label"],
        }
        for c in chunks
        if c["taxonomy"] and c["chunk_id"] not in EXCLUDED_CHUNK_IDS
    ]

    top_clusters = [
        {
            "clusterId": cl["cluster_id"],
            "size": cl["size"],
            "sourceLabels": cl["source_labels"],
            "exampleTexts": cl["example_texts"],
        }
        for cl in sorted(summary["clusters"], key=lambda c: -c["size"])[:6]
    ]

    output = {
        "generatedAt": "2026-07-27",
        "method": {
            "embeddingModel": "sentence-transformers/all-MiniLM-L6-v2",
            "nliModel": "cross-encoder/nli-MiniLM2-L6-H768",
            "clustering": "DBSCAN (cosine, eps=0.15, min_samples=2)",
            "sentiment": "NLTK VADER",
        },
        "corpus": {
            "totalChunks": summary["total_chunks"],
            "uniqueChunks": summary["unique_chunks"],
            "duplicateChunks": summary["duplicate_chunks"],
            "clusterCount": len(summary["clusters"]),
        },
        "taxonomyDistribution": summary["taxonomy_distribution"],
        "sentimentDistribution": summary["sentiment_distribution"],
        "findings": findings,
        "topClusters": top_clusters,
        "knownLimitations": [
            "Zero-shot classification (no fine-tuning yet) surfaced high-confidence labels on only 6 of 145 unique chunks — a narrow, single-domain corpus like this gives the entailment model little contrast between related categories. Per the deep-research report, this is the expected first pass before weak supervision / human-reviewed labeling, not a finished classifier.",
            "2 of those 6 tagged chunks were nav artifacts (a breadcrumb trail, a main-menu list) that the automatic nav filter missed because they contain a couple of common words. Excluded manually after review; not shown above.",
            "DBSCAN clustering needed eps tuned down to 0.15 from an initial 0.35 — at looser thresholds, 87% of chunks collapsed into one mega-cluster because general-purpose sentence embeddings don't spread out much across a topically narrow, single-regulator corpus.",
            "Sentiment skews heavily positive (98/135) — VADER is tuned for social-media text; official/marketing copy full of words like 'protect' and 'help' reads as positive regardless of the underlying dealer sentiment. Not a reliable pain signal on this corpus type.",
        ],
    }

    (DATA_DIR / "nlp-analysis.json").write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"Wrote data/nlp-analysis.json — {len(findings)} findings, {len(top_clusters)} clusters")


if __name__ == "__main__":
    main()
