import { Paperclip } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PageFrame, ProductPageHeader } from "@/components/product/page-primitives";
import { EmptyState } from "@/components/product/empty-state";
import { money, StatusBadge } from "@/components/product/status";
import { requireProductActor } from "@/server/auth/guards";
import { EntityLink } from "@/components/product/entity-link";
import { TableToolbar } from "@/components/product/table-toolbar";
import { getExceptionsPage } from "@/server/services/product";

const sorts = [{ value: "impact-desc", label: "Impact high to low" }, { value: "newest", label: "Newest" }, { value: "priority-desc", label: "Priority high to low" }];
export default async function DealerExceptionsPage({ searchParams }: { searchParams: Promise<{ page?: string; q?: string; status?: string; impact?: string; sort?: string }> }) {
  const actor = await requireProductActor(["DEALER_ADMIN", "DEALER_USER"]); const params = await searchParams; const data = getExceptionsPage(actor, { page: Number(params.page ?? 1), query: params.q, status: params.status, impact: params.impact, sort: params.sort });
  return <PageFrame><ProductPageHeader title="Exceptions" description="Explain discrepancies, add evidence, and track reviewer requests without changing the original source record." /><div><TableToolbar searchPlaceholder="Search VIN, rule, or exception ID" filterLabel="Exception status" filterOptions={["NEW","UNDER_REVIEW","AWAITING_DEALER","RESPONSE_RECEIVED","REVIEWER_ACTION","RESOLVED","ESCALATED"].map((value) => ({ value, label: value.replaceAll("_", " ") }))} sortOptions={sorts} defaultSort="impact-desc" page={data.page} pageCount={data.pageCount} total={data.total} /><section className="overflow-hidden rounded-b-[14px] border bg-white">{data.rows.length ? <><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead>Exception</TableHead><TableHead>VIN</TableHead><TableHead>Status</TableHead><TableHead>Priority</TableHead><TableHead className="text-right">Estimated impact</TableHead><TableHead><span className="sr-only">Action</span></TableHead></TableRow></TableHeader><TableBody>{data.rows.map((item) => <TableRow key={item.id}><TableCell><EntityLink type="exception" id={item.id} className="max-w-md">{item.summary}</EntityLink><p className="max-w-lg text-xs text-muted-foreground">{item.explanation}</p></TableCell><TableCell className="font-mono text-xs">{item.transactionId ? <EntityLink type="transaction" id={item.transactionId} appearance="secondary">…{item.vin.slice(-8)}</EntityLink> : `…${item.vin.slice(-8)}`}</TableCell><TableCell><StatusBadge value={item.status} /></TableCell><TableCell><StatusBadge value={item.priority} /></TableCell><TableCell className="text-right font-mono">{money(item.estimatedFeeImpact)}</TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" asChild><EntityLink type="exception" id={item.id} appearance="action"><Paperclip className="size-4" /> Review</EntityLink></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y md:hidden">{data.rows.map((item) => <article key={item.id} className="p-4"><EntityLink type="exception" id={item.id}>{item.summary}</EntityLink><p className="mt-1 text-xs text-muted-foreground">…{item.vin.slice(-8)} · {item.ruleId}</p><div className="mt-3 flex items-center justify-between gap-3"><StatusBadge value={item.status} /><strong className="text-[13px] font-medium">{money(item.estimatedFeeImpact)}</strong></div></article>)}</div></> : <EmptyState kind="all-clear" title={params.q || params.status || params.impact ? "No exceptions match these filters" : "No open exceptions"} description={params.q || params.status || params.impact ? "Clear or change the filters to return to the exception queue." : "New discrepancies will appear here after reconciliation runs."} compact />}</section></div></PageFrame>;
}
