import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PageFrame, ProductPageHeader } from "@/components/product/page-primitives";
import { EmptyState } from "@/components/product/empty-state";
import { dateLabel, money, StatusBadge } from "@/components/product/status";
import { TableToolbar } from "@/components/product/table-toolbar";
import { parseDatasetSort } from "@/domain/product/ui-system";
import { requireProductActor } from "@/server/auth/guards";
import { getReviewerProductData } from "@/server/services/product";
import { EntityLink } from "@/components/product/entity-link";

const sorts = [{ value: "attention", label: "Attention" }, { value: "name-asc", label: "Name A–Z" }, { value: "match-desc", label: "Match rate high to low" }];
export default async function ReviewerDealershipsPage({ searchParams }: { searchParams: Promise<{ q?: string; sort?: string }> }) {
  await requireProductActor(["REGULATOR_REVIEWER"]); const params = await searchParams; const data = getReviewerProductData(); const query = params.q?.trim().toLowerCase(); const sort = parseDatasetSort("reviewerDealerships", params.sort); const filtered = data.dealerships.filter((item) => !query || item.tradeName.toLowerCase().includes(query) || item.registrationNumber.toLowerCase().includes(query)); const rows = [...filtered].sort((a,b) => sort === "name-asc" ? a.tradeName.localeCompare(b.tradeName) || a.id.localeCompare(b.id) : sort === "match-desc" ? (b.matchRate ?? -1) - (a.matchRate ?? -1) || a.id.localeCompare(b.id) : b.highPriority - a.highPriority || b.openExceptions - a.openExceptions || a.id.localeCompare(b.id));
  return <PageFrame><ProductPageHeader title="Dealerships" description="Operational review status across the dealerships available to your organization." /><div><TableToolbar searchPlaceholder="Search name or registration" sortOptions={sorts} defaultSort="attention" page={1} pageCount={1} total={rows.length} /><section className="overflow-hidden rounded-b-[14px] border bg-white">{rows.length ? <><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead>Dealership</TableHead><TableHead>Registration</TableHead><TableHead>Location</TableHead><TableHead>Latest run</TableHead><TableHead>Match rate</TableHead><TableHead>Open items</TableHead><TableHead className="text-right">Impact</TableHead></TableRow></TableHeader><TableBody>{rows.map((item) => <TableRow key={item.id}><TableCell><EntityLink type="dealership" id={item.id}>{item.tradeName}</EntityLink></TableCell><TableCell className="font-mono text-xs">{item.registrationNumber}</TableCell><TableCell>{item.city}, {item.province}</TableCell><TableCell>{dateLabel(item.lastRunAt)}</TableCell><TableCell>{item.matchRate === null ? <StatusBadge value="No run" /> : `${item.matchRate}%`}</TableCell><TableCell>{item.openExceptions}</TableCell><TableCell className="text-right font-mono">{money(item.estimatedFeeImpact)}</TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y md:hidden">{rows.map((item) => <article key={item.id} className="p-4"><EntityLink type="dealership" id={item.id}>{item.tradeName}</EntityLink><p className="mt-1 text-xs text-muted-foreground">{item.registrationNumber} · {item.city}, {item.province}</p><div className="mt-3 flex items-center justify-between"><span className="text-[13px]">{item.matchRate === null ? "No run" : `${item.matchRate}% match`}</span><strong className="text-[13px] font-medium">{item.openExceptions} open</strong></div></article>)}</div></> : <EmptyState kind="no-dealerships" title={query ? "No dealerships match this search" : "No dealerships yet"} description={query ? "Change the search to return to the accessible portfolio." : "Dealerships appear when they are assigned to your review organization."} compact />}</section></div></PageFrame>;
}
